Feature 1
musyelevateher/TRAVEL-WEBSITE-II pull request #1
Opened 2024-10-02 15:54 UTC by musyelevateher

Added "Html and CSS" to the webpage

2024-10-02 19:25 UTC, Devsalmasaeed requested changes

2024-10-02 19:25 UTC, Devsalmasaeed commented on style.css
> +}
Hi @musyelevateher,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️
- Make your HTML truly semantic, ensure that the HTML tags correctly describe the content's meaning and structure.
- Please use professional PR title
- Make your design UI like the Figma design

# Figma design

![image](https://github.com/user-attachments/assets/2fdf7960-6e56-471c-98b9-d8397368488e)


![image](https://github.com/user-attachments/assets/7e9b1f95-b7c8-47f5-86c1-4cd7d33b2b3c)

# Your design


![image](https://github.com/user-attachments/assets/2b22c86d-09dc-41e6-92e8-433f4a610312)


![image](https://github.com/user-attachments/assets/f85b03ef-1145-431b-8f2f-6fb5dbf47d60)




Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-04 17:16 UTC, Xfarouq commented on index.html
> +              <div class="location">
Why are your closing div tags arranged like this? This method isn't applicable for best practice, please make sure to rectify it

2024-10-04 17:20 UTC, Xfarouq requested changes
Hi @musyelevateher 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    <img src="https://camo.githubusercontent.com/7cf1ba8db9cd08f454a9651e48128c064a4440a59881658c8593a41a8de243f3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966" alt="Remote Collaboration" style="width:40%;">
</div>

### To Highlight 💯
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️
- **Make sure to have a clean code always**
- Please make sure to follow exactly how the mobile view was implemented in the tutorial video 🙏
- The mobile view is okay , but don't specify a width to it except to use media queries for that


### Optional Suggestions
**I strongly recommend you to watch the tutorial videos very well please for the mobile first approach

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-10 13:09 UTC, Devsalmasaeed approved these changes

2024-10-10 13:09 UTC, Devsalmasaeed commented on style.css
> +}
Hi @musyelevateher,

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    <img src="https://media1.giphy.com/media/gLu90OMjz4j3hAkJk2/giphy.gif?cid=47028fa8sx12d824xrvy8zo8bq3w00f23hoj11gqqzus7q0f&ep=v1_gifs&rid=giphy.gif&ct=g" alt="Remote Collaboration" style="width:100%;">
</div>

### Highlights
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

2024-10-11 17:16 UTC, merged